/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SituacoesRouteImport } from './routes/situacoes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as PessoasRouteImport } from './routes/pessoas'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as MapaIlhasRouteImport } from './routes/mapa-ilhas'
import { Route as IlhasRouteImport } from './routes/ilhas'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as FuncoesRouteImport } from './routes/funcoes'
import { Route as FeriasRouteImport } from './routes/ferias'
import { Route as DistribuicaoRouteImport } from './routes/distribuicao'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GestaoIndexRouteImport } from './routes/gestao.index'
import { Route as GestaoPlanejamentoRouteImport } from './routes/gestao.planejamento'
import { Route as GestaoPessoasRouteImport } from './routes/gestao.pessoas'
import { Route as GestaoOperacaoRouteImport } from './routes/gestao.operacao'
import { Route as GestaoConteudosRouteImport } from './routes/gestao.conteudos'

const SituacoesRoute = SituacoesRouteImport.update({
  id: '/situacoes',
  path: '/situacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoasRoute = PessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaIlhasRoute = MapaIlhasRouteImport.update({
  id: '/mapa-ilhas',
  path: '/mapa-ilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const IlhasRoute = IlhasRouteImport.update({
  id: '/ilhas',
  path: '/ilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncoesRoute = FuncoesRouteImport.update({
  id: '/funcoes',
  path: '/funcoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FeriasRoute = FeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuicaoRoute = DistribuicaoRouteImport.update({
  id: '/distribuicao',
  path: '/distribuicao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoIndexRoute = GestaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoPlanejamentoRoute = GestaoPlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoPessoasRoute = GestaoPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoOperacaoRoute = GestaoOperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoConteudosRoute = GestaoConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => GestaoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conteudos': typeof ConteudosRoute
  '/distribuicao': typeof DistribuicaoRoute
  '/ferias': typeof FeriasRoute
  '/funcoes': typeof FuncoesRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/ilhas': typeof IlhasRoute
  '/mapa-ilhas': typeof MapaIlhasRoute
  '/performance': typeof PerformanceRoute
  '/pessoas': typeof PessoasRoute
  '/planejamento': typeof PlanejamentoRoute
  '/programas': typeof ProgramasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/situacoes': typeof SituacoesRoute
  '/gestao/conteudos': typeof GestaoConteudosRoute
  '/gestao/operacao': typeof GestaoOperacaoRoute
  '/gestao/pessoas': typeof GestaoPessoasRoute
  '/gestao/planejamento': typeof GestaoPlanejamentoRoute
  '/gestao/': typeof GestaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conteudos': typeof ConteudosRoute
  '/distribuicao': typeof DistribuicaoRoute
  '/ferias': typeof FeriasRoute
  '/funcoes': typeof FuncoesRoute
  '/ilhas': typeof IlhasRoute
  '/mapa-ilhas': typeof MapaIlhasRoute
  '/performance': typeof PerformanceRoute
  '/pessoas': typeof PessoasRoute
  '/planejamento': typeof PlanejamentoRoute
  '/programas': typeof ProgramasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/situacoes': typeof SituacoesRoute
  '/gestao/conteudos': typeof GestaoConteudosRoute
  '/gestao/operacao': typeof GestaoOperacaoRoute
  '/gestao/pessoas': typeof GestaoPessoasRoute
  '/gestao/planejamento': typeof GestaoPlanejamentoRoute
  '/gestao': typeof GestaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conteudos': typeof ConteudosRoute
  '/distribuicao': typeof DistribuicaoRoute
  '/ferias': typeof FeriasRoute
  '/funcoes': typeof FuncoesRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/ilhas': typeof IlhasRoute
  '/mapa-ilhas': typeof MapaIlhasRoute
  '/performance': typeof PerformanceRoute
  '/pessoas': typeof PessoasRoute
  '/planejamento': typeof PlanejamentoRoute
  '/programas': typeof ProgramasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/situacoes': typeof SituacoesRoute
  '/gestao/conteudos': typeof GestaoConteudosRoute
  '/gestao/operacao': typeof GestaoOperacaoRoute
  '/gestao/pessoas': typeof GestaoPessoasRoute
  '/gestao/planejamento': typeof GestaoPlanejamentoRoute
  '/gestao/': typeof GestaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conteudos'
    | '/distribuicao'
    | '/ferias'
    | '/funcoes'
    | '/gestao'
    | '/ilhas'
    | '/mapa-ilhas'
    | '/performance'
    | '/pessoas'
    | '/planejamento'
    | '/programas'
    | '/sitemap.xml'
    | '/situacoes'
    | '/gestao/conteudos'
    | '/gestao/operacao'
    | '/gestao/pessoas'
    | '/gestao/planejamento'
    | '/gestao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conteudos'
    | '/distribuicao'
    | '/ferias'
    | '/funcoes'
    | '/ilhas'
    | '/mapa-ilhas'
    | '/performance'
    | '/pessoas'
    | '/planejamento'
    | '/programas'
    | '/sitemap.xml'
    | '/situacoes'
    | '/gestao/conteudos'
    | '/gestao/operacao'
    | '/gestao/pessoas'
    | '/gestao/planejamento'
    | '/gestao'
  id:
    | '__root__'
    | '/'
    | '/conteudos'
    | '/distribuicao'
    | '/ferias'
    | '/funcoes'
    | '/gestao'
    | '/ilhas'
    | '/mapa-ilhas'
    | '/performance'
    | '/pessoas'
    | '/planejamento'
    | '/programas'
    | '/sitemap.xml'
    | '/situacoes'
    | '/gestao/conteudos'
    | '/gestao/operacao'
    | '/gestao/pessoas'
    | '/gestao/planejamento'
    | '/gestao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConteudosRoute: typeof ConteudosRoute
  DistribuicaoRoute: typeof DistribuicaoRoute
  FeriasRoute: typeof FeriasRoute
  FuncoesRoute: typeof FuncoesRoute
  GestaoRoute: typeof GestaoRouteWithChildren
  IlhasRoute: typeof IlhasRoute
  MapaIlhasRoute: typeof MapaIlhasRoute
  PerformanceRoute: typeof PerformanceRoute
  PessoasRoute: typeof PessoasRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  ProgramasRoute: typeof ProgramasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SituacoesRoute: typeof SituacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/situacoes': {
      id: '/situacoes'
      path: '/situacoes'
      fullPath: '/situacoes'
      preLoaderRoute: typeof SituacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoas': {
      id: '/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof PessoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-ilhas': {
      id: '/mapa-ilhas'
      path: '/mapa-ilhas'
      fullPath: '/mapa-ilhas'
      preLoaderRoute: typeof MapaIlhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilhas': {
      id: '/ilhas'
      path: '/ilhas'
      fullPath: '/ilhas'
      preLoaderRoute: typeof IlhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcoes': {
      id: '/funcoes'
      path: '/funcoes'
      fullPath: '/funcoes'
      preLoaderRoute: typeof FuncoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferias': {
      id: '/ferias'
      path: '/ferias'
      fullPath: '/ferias'
      preLoaderRoute: typeof FeriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuicao': {
      id: '/distribuicao'
      path: '/distribuicao'
      fullPath: '/distribuicao'
      preLoaderRoute: typeof DistribuicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/': {
      id: '/gestao/'
      path: '/'
      fullPath: '/gestao/'
      preLoaderRoute: typeof GestaoIndexRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/planejamento': {
      id: '/gestao/planejamento'
      path: '/planejamento'
      fullPath: '/gestao/planejamento'
      preLoaderRoute: typeof GestaoPlanejamentoRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/pessoas': {
      id: '/gestao/pessoas'
      path: '/pessoas'
      fullPath: '/gestao/pessoas'
      preLoaderRoute: typeof GestaoPessoasRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/operacao': {
      id: '/gestao/operacao'
      path: '/operacao'
      fullPath: '/gestao/operacao'
      preLoaderRoute: typeof GestaoOperacaoRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/conteudos': {
      id: '/gestao/conteudos'
      path: '/conteudos'
      fullPath: '/gestao/conteudos'
      preLoaderRoute: typeof GestaoConteudosRouteImport
      parentRoute: typeof GestaoRoute
    }
  }
}

interface GestaoRouteChildren {
  GestaoConteudosRoute: typeof GestaoConteudosRoute
  GestaoOperacaoRoute: typeof GestaoOperacaoRoute
  GestaoPessoasRoute: typeof GestaoPessoasRoute
  GestaoPlanejamentoRoute: typeof GestaoPlanejamentoRoute
  GestaoIndexRoute: typeof GestaoIndexRoute
}

const GestaoRouteChildren: GestaoRouteChildren = {
  GestaoConteudosRoute: GestaoConteudosRoute,
  GestaoOperacaoRoute: GestaoOperacaoRoute,
  GestaoPessoasRoute: GestaoPessoasRoute,
  GestaoPlanejamentoRoute: GestaoPlanejamentoRoute,
  GestaoIndexRoute: GestaoIndexRoute,
}

const GestaoRouteWithChildren =
  GestaoRoute._addFileChildren(GestaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConteudosRoute: ConteudosRoute,
  DistribuicaoRoute: DistribuicaoRoute,
  FeriasRoute: FeriasRoute,
  FuncoesRoute: FuncoesRoute,
  GestaoRoute: GestaoRouteWithChildren,
  IlhasRoute: IlhasRoute,
  MapaIlhasRoute: MapaIlhasRoute,
  PerformanceRoute: PerformanceRoute,
  PessoasRoute: PessoasRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  ProgramasRoute: ProgramasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SituacoesRoute: SituacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
